import React from 'react';
import '../styles/index.css';

export const viewport = {
  width: 'device-width',
  initialScale: 1,
};

export const metadata = {
  title: {
    default: 'Viral Video Academy',                           
    template: 'Viral Video Academy | %s',                     
  },
  description: 'Master viral video creation with expert Ukrainian courses. Learn proven strategies to monetize content, build audience, and create engaging videos that generate income.',
  keywords: 'viral videos, video creation course, content monetization, Ukrainian video course, social media marketing, video editing, content creator',
  
  openGraph: {
    type: 'website',
    title: {
      default: 'Viral Video Academy',                        
      template: 'Viral Video Academy | %s',                 
    },
    description: 'Transform your video creation skills with our comprehensive Ukrainian course. Learn to create viral content and build a profitable online presence.',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}

        <script type="module" src="https://static.rocket.new/rocket-web.js?_cfg=https%3A%2F%2Fludasapp7464back.builtwithrocket.new&_be=https%3A%2F%2Fapplication.rocket.new&_v=0.1.9" />
        <script type="module" src="https://static.rocket.new/rocket-shot.js?v=0.0.1" /></body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


